import { z } from 'zod';
import type { Tipologia } from '@/erp/types';

export const proyectoSchema = z.object({
  id: z.string(),
  nombre: z.string(),
  ubicacion: z.string(),
  tipologia: z.enum(['residencial','comercial','industrial','civil','publica'] as const),
  presupuestoTotal: z.number().default(0),
  montoContrato: z.number().default(0),
  cliente: z.string().default(''),
  presupuestoActualId: z.string().nullable().optional(),
  fechaInicio: z.string().default(''),
  fechaFin: z.string().default(''),
  fechaInicioReal: z.string().optional().default(''),
  fechaFinEstimada: z.string().optional().default(''),
  avanceFisico: z.number().default(0),
  avanceFinanciero: z.number().default(0),
  estado: z.enum(['planeacion','ejecucion','pausado','finalizado'] as const).default('planeacion'),
  descripcion: z.string().optional().default(''),
  tipoObra: z.enum(['nueva','remodelacion','ampliacion'] as const).optional().default('nueva'),
  clienteNit: z.string().optional().default(''),
  clienteTelefono: z.string().optional().default(''),
  clienteEmail: z.string().optional().default(''),
  direccion: z.string().optional().default(''),
  ciudad: z.string().optional().default(''),
  departamento: z.string().optional().default(''),
  codigoPostal: z.string().optional().default(''),
  pais: z.string().optional().default('Guatemala'),
  areaConstruccion: z.number().optional(),
  numPisos: z.number().optional(),
  plazoSemanas: z.number().optional(),
  ingenieroResidente: z.string().optional().default(''),
  supervisor: z.string().optional().default(''),
  arquitecto: z.string().optional().default(''),
  numeroExpediente: z.string().optional().default(''),
  numeroLicencia: z.string().optional().default(''),
  margenUtilidadObjetivo: z.number().optional(),
  moneda: z.enum(['GTQ','USD'] as const).optional().default('GTQ'),
  etapa: z.enum(['planificacion','diseno','preconstruccion','construccion','cierre'] as const).optional().default('planificacion'),
  lat: z.number().nullable().optional(),
  lng: z.number().nullable().optional(),
  latitud: z.number().nullable().optional(),
  longitud: z.number().nullable().optional(),
  factorSobrecosto: z.object({
    indirectos: z.number(),
    administracion: z.number(),
    imprevistos: z.number(),
    utilidad: z.number(),
  }).optional(),
}).transform(d => ({
  ...d,
  lat: d.lat ?? d.latitud ?? 14.6349,
  lng: d.lng ?? d.longitud ?? -90.5069,
  fechaInicio: d.fechaInicio ?? '',
  fechaFin: d.fechaFin ?? '',
  presupuestoActualId: d.presupuestoActualId ?? undefined,
}));

export type ProyectoStore = z.infer<typeof proyectoSchema>;