import { expect, vi } from 'vitest';
import * as matchers from 'vitest-axe/matchers';

expect.extend(matchers);

export const createMockStore = (overrides: Record<string, any> = {}) => ({
  proyectos: [],
  currentProjectId: null,
  setCurrentProjectId: () => {},
  proveedores: [],
  compras: [],
  activos: [],
  cuadros: [],
  pagosProveedor: [],
  ventasPaquetes: [],
  anticipos: [],
  cajasChicas: [],
  rendimientosCampo: [],
  cotizaciones: [],
  hitos: [],
  ordenesCambio: [],
  riesgos: [],
  auditoria: [],
  reportes: [],
  notificaciones: [],
  errores: [],
  apiKeys: [],
  eventos: [],
  bitacoras: [],
  presupuestos: [],
  user: undefined,
  addVentaPaquete: async () => {},
  updateVentaPaquete: async () => {},
  addAnticipo: async () => {},
  updateAnticipo: async () => {},
  deleteAnticipo: async () => {},
  addCajaChica: async () => {},
  updateCajaChica: async () => {},
  deleteCajaChica: async () => {},
  setActivos: (fn: any) => fn([]),
  setCuadros: (fn: any) => fn([]),
  setPagosProveedor: (fn: any) => fn([]),
  ...overrides,
});
