-- COPIAR Y PEGAR ESTO EN SUPABASE SQL EDITOR
-- SIN COMENTARIOS, SIN QUERIES - SOLO ESTAS LÍNEAS

ALTER TABLE erp_proyectos REPLICA IDENTITY FULL;
ALTER TABLE erp_movimientos REPLICA IDENTITY FULL;
ALTER TABLE erp_empleados REPLICA IDENTITY FULL;
ALTER TABLE erp_materiales REPLICA IDENTITY FULL;
ALTER TABLE erp_ordenes_compra REPLICA IDENTITY FULL;
ALTER TABLE erp_proveedores REPLICA IDENTITY FULL;
ALTER TABLE erp_eventos_calendario REPLICA IDENTITY FULL;
ALTER TABLE erp_bitacora REPLICA IDENTITY FULL;
ALTER TABLE erp_presupuestos REPLICA IDENTITY FULL;
ALTER TABLE erp_avances REPLICA IDENTITY FULL;
ALTER TABLE erp_licitaciones REPLICA IDENTITY FULL;
ALTER TABLE erp_renglones REPLICA IDENTITY FULL;
ALTER TABLE erp_insumos REPLICA IDENTITY FULL;
ALTER TABLE erp_sub_renglones REPLICA IDENTITY FULL;
ALTER TABLE erp_seguimiento REPLICA IDENTITY FULL;
ALTER TABLE erp_vales_salida REPLICA IDENTITY FULL;
ALTER TABLE erp_insumos_base REPLICA IDENTITY FULL;
ALTER TABLE erp_rendimientos_cuadrilla REPLICA IDENTITY FULL;
ALTER TABLE activos_herramientas REPLICA IDENTITY FULL;
ALTER TABLE cuadro_comparativo_proveedores REPLICA IDENTITY FULL;
ALTER TABLE cotizaciones REPLICA IDENTITY FULL;
ALTER TABLE anticipos REPLICA IDENTITY FULL;
ALTER TABLE amortizaciones REPLICA IDENTITY FULL;
ALTER TABLE pagos_proveedores REPLICA IDENTITY FULL;
ALTER TABLE ventas_paquetes REPLICA IDENTITY FULL;
ALTER TABLE centros_costo REPLICA IDENTITY FULL;
ALTER TABLE cajas_chicas REPLICA IDENTITY FULL;
ALTER TABLE destajos REPLICA IDENTITY FULL;
ALTER TABLE logs_sistema REPLICA IDENTITY FULL;
ALTER TABLE erp_auditoria REPLICA IDENTITY FULL;
ALTER TABLE profiles REPLICA IDENTITY FULL;
