-- ACTIVAR REALTIME EN TABLAS QUE FALTAN (DEFAULT → FULL)
-- Ejecutar en Supabase SQL Editor

ALTER TABLE erp_cuentas_cobrar REPLICA IDENTITY FULL;
ALTER TABLE erp_cuentas_pagar REPLICA IDENTITY FULL;
ALTER TABLE erp_hitos REPLICA IDENTITY FULL;
ALTER TABLE erp_incidentes REPLICA IDENTITY FULL;
ALTER TABLE erp_liberaciones_partida REPLICA IDENTITY FULL;
ALTER TABLE erp_muro REPLICA IDENTITY FULL;
ALTER TABLE erp_no_conformidades REPLICA IDENTITY FULL;
ALTER TABLE erp_ordenes_cambio REPLICA IDENTITY FULL;
ALTER TABLE erp_pruebas_laboratorio REPLICA IDENTITY FULL;
ALTER TABLE erp_riesgos REPLICA IDENTITY FULL;
