name: Deploy to GitHub Pages

on:
  push:
    branches: ['master']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_KEY: ${{ secrets.VITE_SUPABASE_KEY }}
      - name: Copy to docs
        run: |
          git checkout master
          cp -r dist/* docs/
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist